name: 'PR Notes'
description: 'Adds changelog to your pull request'
author: 'enzorenz'
inputs:
  token:
    required: true
    description: 'GitHub Token to use for this action'
  source-branch:
    description: 'Head branch of the pull request'
    required: true
  target-branch: 
    description: 'Base branch of the pull request'
    required: true 
  draft: 
    description: 'Set created pull request status to draft'
    default: 'false'
    required: false
  title:
    description: 'Title for creating pull request (ignored if PR already exists)'
    required: true 
  body:
    description: 'Body for pull request'
    default: ''
    required: false 
  resolve-line-keyword: 
    description: 'Keyword for detecting the resolve line to retrieve related issue/link (case insensitive)'
    default: 'resolves'
    required: false 
  list-title:
    description: 'Title for changes list'
    default: ''
    required: false 
  labels:
    description: 'Labels to add to the PR (comma separated)'
    required: false
  reviewers:
    description: 'Reviewers to request to the PR (comma separated)'
    required: false
  assignees:
    description: 'Assignees to add to the PR (comma separated)'
    required: false
  commit-type-grouping:
    description: 'Groups commits by prefixes (feat, fix, docs, etc.)'
    default: 'false'
    required: false
  exclude-keywords:
    description: 'Exclude PRs with similar keywords (comma separated)'
    required: false
  with-author:
    description: 'Includes commit author in the list'
    default: 'false'
    required: false
  with-checkbox:
    description: 'Adds a checkbox to changelog main items making it a checklist'
    default: 'false'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
