name: E2E Tests

on: push

env:
  NODE_VERSION: 18.18.2
  NODE_ENV: test

jobs:
  checkout-lint:
    runs-on: ubuntu-latest
    container: node:18.18

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            /usr/local/share/.cache/yarn/v4
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: GITHUB NPM package token setup
        run: echo "//npm.pkg.github.com/:_authToken=${TOKEN}" > ~/.npmrc
        env:
          TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Save cache
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            /usr/local/share/.cache/yarn/v4
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

  test-e2e-organization-pt1:
    needs: checkout-lint
    uses: ./.github/workflows/e2e-tests-template.yml
    with:
      test_path: ./test/organization-pt1
      junit_output_dir: test-results/e2e-organization-pt1
